"""
Nuwa.py —— POC 报告生成 + 全栈辐射检测

设计思路：
  - POC 报告：HTML + JSON 双格式，无侵入指标采集
  - 辐射检测：借鉴 CodeGraph 的"关系图谱"思路
    → 改了代码 → 扫描上下游关联文件
    → 检查 DB 迁移 / API 文档 / 测试覆盖 / 配置同步
    → 输出辐射报告（哪些文件需要跟着改）

零依赖（纯标准库）。
"""

import re
import json
import time
import ast
import hashlib
import logging
from pathlib import Path
from dataclasses import dataclass, field, asdict
from typing import Optional

log = logging.getLogger("jinchen.nuwa")


# ════════════════════════════════════════════════════════
#  POC 报告
# ════════════════════════════════════════════════════════
@dataclass
class PocReport:
    """POC 报告数据"""
    title: str
    scenario: str
    steps: list = field(default_factory=list)
    results: dict = field(default_factory=dict)
    verdict: str = "pass"  # pass / fail / partial
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)

    def to_html(self) -> str:
        """生成 HTML 报告"""
        steps_html = "\n".join(
            f"      <li>{i+1}. {s}</li>"
            for i, s in enumerate(self.steps)
        )
        results_rows = "\n".join(
            f"      <tr><td>{k}</td><td>{v}</td></tr>"
            for k, v in self.results.items()
        )
        verdict_color = {"pass": "#4caf50", "fail": "#f44336", "partial": "#ff9800"}.get(
            self.verdict, "#999")
        return f"""<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<title>POC 报告 - {self.title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; }}
  h1 {{ border-bottom: 3px solid #2196f3; padding-bottom: 10px; }}
  .verdict {{ display: inline-block; padding: 4px 12px; border-radius: 4px; color: white; font-weight: bold; background: {verdict_color}; }}
  .meta {{ background: #f5f5f5; padding: 12px; border-radius: 6px; margin: 16px 0; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th {{ background: #e3f2fd; }}
  .footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; color: #999; font-size: 0.85em; }}
</style>
</head>
<body>
  <h1>📊 POC 报告</h1>
  <p><strong>标题：</strong>{self.title}</p>
  <p><strong>场景：</strong>{self.scenario}</p>
  <p><strong>结论：</strong><span class="verdict">{self.verdict.upper()}</span></p>

  <div class="meta">
    <strong>生成时间：</strong>{self.metadata.get('timestamp', time.strftime('%Y-%m-%d %H:%M'))}<br>
    <strong>生成者：</strong>{self.metadata.get('generator', 'jinchen/Nuwa')}<br>
    <strong>版本：</strong>{self.metadata.get('version', '3.2')}
  </div>

  <h2>📋 测试步骤</h2>
  <ol>
{steps_html}
  </ol>

  <h2>📊 结果数据</h2>
  <table>
    <tr><th>指标</th><th>数值</th></tr>
{results_rows}
  </table>

  <h2>📝 备注</h2>
  <p>{self.metadata.get('notes', '无')}</p>

  <div class="footer">
    Generated by jinchen/Nuwa · 无侵入指标采集 · 本地生成
  </div>
</body>
</html>"""

    def save(self, output_dir: str = "poc_reports"):
        out = Path(output_dir)
        out.mkdir(exist_ok=True)
        stem = re.sub(r'[^a-z0-9]+', '_', self.title.lower()).strip('_') or "report"
        ts = time.strftime("%Y%m%d_%H%M%S")

        json_path = out / f"{stem}_{ts}.json"
        html_path = out / f"{stem}_{ts}.html"

        json_path.write_text(
            json.dumps(self.to_dict(), indent=2, ensure_ascii=False),
            encoding="utf-8")
        html_path.write_text(self.to_html(), encoding="utf-8")

        log.info(f"📄 报告已保存: {json_path} | {html_path}")
        return str(json_path), str(html_path)


class Nuwa:
    """
    POC 报告生成器

    用法：
        n = Nuwa("登录接口 POC")
        n.add_step("用正确密码登录 → 期望 200")
        n.add_step("用错误密码登录 → 期望 401")
        n.set_result("成功率", "100%")
        n.set_result("平均响应", "230ms")
        n.verdict = "pass"
        n.save()
    """

    def __init__(self, title: str = "未命名 POC", scenario: str = ""):
        self.title = title
        self.scenario = scenario
        self.steps: list = []
        self.results: dict = {}
        self.verdict: str = "pass"
        self.notes: str = ""
        self.metadata: dict = {
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "generator": "jinchen/Nuwa",
            "version": "3.2",
        }

    def add_step(self, step: str):
        self.steps.append(step)

    def set_result(self, key: str, value):
        self.results[key] = value

    def set_notes(self, text: str):
        self.notes = text
        self.metadata["notes"] = text

    def save(self, output_dir: str = "poc_reports") -> tuple:
        report = PocReport(
            title=self.title, scenario=self.scenario,
            steps=self.steps, results=self.results,
            verdict=self.verdict, metadata=self.metadata,
        )
        return report.save(output_dir)


# ════════════════════════════════════════════════════════
#  全栈辐射检测（借鉴 CodeGraph 关系图谱思路）
# ════════════════════════════════════════════════════════
@dataclass
class RadiationAlert:
    """一条辐射告警"""
    source_file: str
    related_file: str
    alert_type: str       # db_migration / api_doc / unit_test / import / config
    severity: str         # critical / warning / info
    message: str
    suggestion: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


class RadiationDetector:
    """
    全栈辐射检测

    思路（借鉴 CodeGraph 的"关系图谱"）：
    - 代码改动 → 分析影响范围
    - 检查 DB 迁移 / API 文档 / 测试 / 导入 / 配置
    - 输出辐射报告

    不用 tree-sitter，纯 AST + 正则（保持零依赖）。
    但逻辑上模仿 CodeGraph 的"先建图、再查询"。
    """

    def __init__(self, project_root: str = "."):
        self.root = Path(project_root).resolve()
        self._relation_graph: dict = {}  # 文件 → 关联文件列表
        self._build_graph()

    def _build_graph(self):
        """
        构建文件关系图（轻量版 CodeGraph）

        遍历项目，提取：
        - import 关系（A 导入 B → A 依赖 B）
        - 文件命名约定（xxx_api.py ↔ xxx_test.py）
        """
        py_files = list(self.root.rglob("*.py"))
        # 排除非项目目录
        exclude = {".git", "__pycache__", ".venv", "venv", "node_modules",
                   "snapshots", "verdicts", "archive", "feedback", "poc_reports"}
        py_files = [f for f in py_files if not any(p in exclude for p in f.parts)]

        # 建立模块名 → 文件路径映射
        module_map: dict = {}
        for f in py_files:
            rel = f.relative_to(self.root)
            mod = str(rel).replace("/", ".").replace("\\", ".")[:-3]
            if mod.endswith(".__init__"):
                mod = mod[:-9]
            module_map[mod] = f

        # 扫描 import 关系
        for f in py_files:
            self._relation_graph[str(f.relative_to(self.root))] = []
            try:
                content = f.read_text(encoding="utf-8", errors="ignore")
                tree = ast.parse(content)
                for node in ast.walk(tree):
                    if isinstance(node, ast.Import):
                        for n in node.names:
                            self._add_relation(f, n.name, module_map)
                    elif isinstance(node, ast.ImportFrom):
                        mod = node.module or ""
                        self._add_relation(f, mod, module_map)
            except Exception:
                pass

    def _add_relation(self, src_file: Path, mod_name: str, module_map: dict):
        """添加一条关系边"""
        for mod_key in module_map:
            if mod_name == mod_key or mod_name.startswith(mod_key + "."):
                rel_src = str(src_file.relative_to(self.root))
                rel_dst = str(module_map[mod_key].relative_to(self.root))
                if rel_src != rel_dst:
                    if rel_dst not in self._relation_graph.get(rel_src, []):
                        self._relation_graph.setdefault(rel_src, []).append(rel_dst)

    def get_related(self, file_path: str) -> list:
        """查询某个文件的关联文件（CodeGraph 风格查询）"""
        rel = Path(file_path).relative_to(self.root) if str(self.root) in file_path else Path(file_path)
        return self._relation_graph.get(str(rel), [])

    def scan(self, changed_file: str) -> list:
        """
        分析一个改动文件，返回所有辐射告警

        检测维度：
        1. DB 辐射：SQL 改了 → 检查 migrations
        2. API 辐射：路由改了 → 检查 docs
        3. 测试辐射：函数改了 → 检查 tests
        4. 导入辐射：模块改了 → 检查 importer
        5. 配置辐射：env 改了 → 检查 .env.example
        """
        alerts = []
        path = Path(changed_file)
        if not path.exists():
            return alerts

        content = path.read_text(encoding="utf-8", errors="ignore")

        alerts.extend(self._check_db(path, content))
        alerts.extend(self._check_api(path, content))
        alerts.extend(self._check_test(path, content))
        alerts.extend(self._check_import(path, content))
        alerts.extend(self._check_config(path, content))

        return alerts

    def _check_db(self, path: Path, content: str) -> list:
        alerts = []
        has_sql = bool(re.search(
            r'\b(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)\b', content, re.I))
        if not has_sql:
            return alerts

        migration_dirs = ["migrations", "alembic/versions", "db/migrate", "db/migrations"]
        all_migrations = []
        for d in migration_dirs:
            dd = self.root / d
            if dd.exists():
                all_migrations.extend(dd.glob("*.py"))

        if not all_migrations:
            # 有 SQL 但没有 migration 目录/文件
            alerts.append(RadiationAlert(
                source_file=str(path), related_file="migrations/",
                alert_type="db_migration", severity="critical",
                message="检测到 SQL 操作，但缺少 migration 文件",
                suggestion="在 migrations/ 下创建迁移文件同步表结构变更",
            ))
        else:
            # 检查是否有比源文件新的 migration
            path_mtime = path.stat().st_mtime
            newer = [m for m in all_migrations if m.stat().st_mtime > path_mtime]
            if not newer:
                latest = max(all_migrations, key=lambda f: f.stat().st_mtime)
                alerts.append(RadiationAlert(
                    source_file=str(path), related_file=str(latest),
                    alert_type="db_migration", severity="critical",
                    message=f"SQL 文件已修改，但最近的 migration 比它旧（或无更新）",
                    suggestion="创建新的 migration 文件同步表结构变更",
                ))
        return alerts

    def _check_api(self, path: Path, content: str) -> list:
        alerts = []
        has_route = bool(re.search(
            r'@app\.(get|post|put|delete|route)|@router\.(get|post|put|delete)', content))
        if not has_route:
            return alerts

        doc_files = (list(self.root.glob("docs/**/*.md")) +
                     list(self.root.glob("**/API*.md")) +
                     list(self.root.glob("**/api*.yaml")) +
                     list(self.root.glob("**/openapi*.json")))
        if not doc_files:
            alerts.append(RadiationAlert(
                source_file=str(path), related_file="docs/",
                alert_type="api_doc", severity="warning",
                message="检测到 API 路由变更，但未找到接口文档",
                suggestion="更新 docs/API.md 或生成 OpenAPI Schema",
            ))
        return alerts

    def _check_test(self, path: Path, content: str) -> list:
        alerts = []
        if path.parent.name == "tests" or path.parent.name == "test":
            return alerts

        funcs = re.findall(r'def\s+(\w+)\s*\(', content)
        if not funcs:
            return alerts

        test_dirs = ["tests", "test", "__tests__"]
        test_files = []
        for td in test_dirs:
            tdp = self.root / td
            if tdp.exists():
                test_files.extend(tdp.glob("*.py"))

        if not test_files:
            alerts.append(RadiationAlert(
                source_file=str(path), related_file="tests/",
                alert_type="unit_test", severity="warning",
                message=f"修改了 {len(funcs)} 个函数，但未找到对应测试文件",
                suggestion=f"为以下函数添加单元测试: {', '.join(funcs[:5])}",
            ))
        else:
            test_content = " ".join(f.read_text(errors="ignore") for f in test_files)
            uncovered = [f for f in funcs if f not in test_content]
            if uncovered:
                alerts.append(RadiationAlert(
                    source_file=str(path), related_file="tests/",
                    alert_type="unit_test", severity="info",
                    message=f"以下函数可能缺少测试覆盖: {', '.join(uncovered[:5])}",
                    suggestion="补充单元测试以提高覆盖率",
                ))
        return alerts

    def _check_import(self, path: Path, content: str) -> list:
        alerts = []
        if path.stem == "__init__":
            return alerts

        module_name = path.stem
        for py_file in self.root.rglob("*.py"):
            if py_file == path or "tests" in py_file.parts:
                continue
            fc = py_file.read_text(errors="ignore")
            if re.search(rf'from\s+\S*{module_name}\S*\s+import|import\s+\S*{module_name}\S*', fc):
                alerts.append(RadiationAlert(
                    source_file=str(path), related_file=str(py_file),
                    alert_type="import", severity="info",
                    message=f"{py_file.name} 导入了 {module_name}，可能需要同步适配",
                    suggestion="检查导入方的调用是否兼容本次修改",
                ))
        return alerts

    def _check_config(self, path: Path, content: str) -> list:
        alerts = []
        env_vars = set(re.findall(r'os\.getenv\("(\w+)"\)|os\.environ\["(\w+)"\]', content))
        env_vars = {v for v in env_vars if v}
        if not env_vars:
            return alerts

        env_example = self.root / ".env.example"
        if not env_example.exists():
            alerts.append(RadiationAlert(
                source_file=str(path), related_file=".env.example",
                alert_type="config", severity="warning",
                message=f"使用了 {len(env_vars)} 个环境变量，但缺少 .env.example",
                suggestion=f"创建 .env.example 并添加: {', '.join(sorted(env_vars)[:5])}",
            ))
        else:
            existing = env_example.read_text()
            missing = [v for v in sorted(env_vars) if v not in existing]
            if missing:
                alerts.append(RadiationAlert(
                    source_file=str(path), related_file=".env.example",
                    alert_type="config", severity="info",
                    message=f".env.example 缺少变量: {', '.join(missing)}",
                    suggestion=f"补充: {', '.join(missing)}",
                ))
        return alerts

    def generate_report(self, alerts: list) -> str:
        """生成辐射报告（Markdown）"""
        if not alerts:
            return "## ✅ 辐射检测通过\n\n未发现上下游遗漏。"

        by_severity = {"critical": [], "warning": [], "info": []}
        for a in alerts:
            by_severity.get(a.severity, by_severity["info"]).append(a)

        lines = ["## ⚠️ 全栈辐射检测报告\n"]
        for sev, icon in [("critical", "🔴"), ("warning", "🟡"), ("info", "🔵")]:
            items = by_severity[sev]
            if not items:
                continue
            lines.append(f"\n### {icon} {sev.upper()} ({len(items)})\n")
            for a in items:
                lines.append(f"- **{a.alert_type}** `{a.source_file}`")
                lines.append(f"  - {a.message}")
                lines.append(f"  - 💡 {a.suggestion}")
        return "\n".join(lines)

    def graph_stats(self) -> dict:
        """关系图谱统计"""
        total_edges = sum(len(v) for v in self._relation_graph.values())
        return {
            "files": len(self._relation_graph),
            "edges": total_edges,
            "avg_dependencies": round(total_edges / max(len(self._relation_graph), 1), 1),
        }


# ════════════════════════════════════════════════════════
#  CLI 入口
# ════════════════════════════════════════════════════════
if __name__ == "__main__":
    import argparse
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    parser = argparse.ArgumentParser(description="Nuwa —— POC 报告 + 辐射检测")
    parser.add_argument("action", choices=["poc", "radiate", "graph"])
    parser.add_argument("--file", "-f", help="目标文件")
    parser.add_argument("--root", "-r", default=".", help="项目根目录")
    parser.add_argument("--output", "-o", default="poc_reports", help="输出目录")
    args = parser.parse_args()

    if args.action == "poc":
        n = Nuwa(title="命令行 POC", scenario="交互式创建")
        print("📝 输入测试步骤（空行结束）：")
        while True:
            line = input("  > ").strip()
            if not line:
                break
            n.add_step(line)
        n.set_result("步骤数", str(len(n.steps)))
        n.verdict = input("结论 (pass/fail/partial): ").strip() or "pass"
        paths = n.save(args.output)
        print(f"✅ 报告: {paths}")

    elif args.action == "radiate":
        if not args.file:
            print("❌ 请指定 --file")
            sys.exit(1)
        rd = RadiationDetector(project_root=args.root)
        alerts = rd.scan(args.file)
        print(rd.generate_report(alerts))

    elif args.action == "graph":
        rd = RadiationDetector(project_root=args.root)
        stats = rd.graph_stats()
        print(f"📊 文件数: {stats['files']}")
        print(f"📊 关系边数: {stats['edges']}")
        print(f"📊 平均依赖: {stats['avg_dependencies']}")
        print(f"\n🔗 关系示例（前 5 条）：")
        count = 0
        for src, dsts in list(rd._relation_graph.items())[:5]:
            for dst in dsts[:3]:
                print(f"  {src} → {dst}")
                count += 1
            if count >= 5:
                break
